FROM python:3.10.12

WORKDIR /app

RUN pip install --no-cache-dir poetry
ENV POETRY_VIRTUALENVS_IN_PROJECT=false \
	POETRY_VIRTUALENVS_PATH=/opt/poetry-virtualenvs

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root

COPY . .

EXPOSE 8000

CMD ["poetry", "run", "fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "8000"]